### ISSUE TITLE
[Reminder] Bot API 2.1 update

### ISSUE THREAD

**Issue by Kondra007** [eternnoir/pyTelegramBotAPI#169]
Bot API got a big update, changelog's [here](https://core.telegram.org/bots/api#recent-changes)

- [x] `edited_message` field in `Update` object  (See #171)
- [x] `edit_date` field in `Message` object (See #170)
- [x] `user` field in `MessageEntity` object (See #172)
- [x] getChat
- [x] leaveChat
- [x] getChatAdministrators
- [x] getChatMember
- [x] getChatMembersCount

**Comment by eternnoir** [comment]
These changes will wait branch v3 complete.

**Comment by pevdh** [comment]
Implemented since d2e7f4d8f2372810546d28cebf4e943763621ecb :)
